#!/usr/bin/env python3
"""Full-annulus cylinder case with hyper dual-velocity equations.

Uses a structured annulus mesh generated by:
  apps/cylinder/grid_generation/run_generate_full.sh

Topology (single block):
- direction 1: angular periodic boundaries
- direction 0, side 0: inner wall (cylinder)
- direction 0, side 1: outer farfield
"""

import os
from pathlib import Path
import h5py
from sympy import Eq, S
from opensbli import *
from opensbli.physical_models.hyper_dual_velocity_physics import HyperDualVelocitySplit

grid_path = Path(__file__).with_name('data.h5')
with h5py.File(grid_path, 'r') as _f:
    _dset = _f['opensbliblock00']['x0_B0']
    _shape = _dset.shape
    _size = _dset.attrs.get('size')
if len(_shape) != 2:
    raise RuntimeError(f'Expected 2D grid in {grid_path}, found shape {_shape}')

# Prefer explicit interior-size metadata when available; fallback to shape mapping.
if _size is not None and len(_size) == 2:
    mesh_np0_default = str(int(_size[0]))
    mesh_np1_default = str(int(_size[1]))
else:
    mesh_np0_default = str(_shape[1])
    mesh_np1_default = str(_shape[0])

simulation_parameters = {
    'gama': os.getenv('GAMMA_VALUE', '1.4'),
    'Minf': os.getenv('MINF_VALUE', '2.0'),
    'Pr': os.getenv('PR_VALUE', '0.71'),
    'Re': os.getenv('RE_VALUE', '1.0e4'),
    'Ml': os.getenv('ML_VALUE', '0.0'),
    'dt': os.getenv('DT_VALUE', '1.0e-5'),
    'niter': os.getenv('NITER_VALUE', '200'),
    'Twall': os.getenv('TWALL_VALUE', '1.0'),
    'SuthT': os.getenv('SUTHT_VALUE', '110.4'),
    'RefT': os.getenv('REFT_VALUE', '273.15'),
    'block0np0': os.getenv('NP0_VALUE', mesh_np0_default),
    'block0np1': os.getenv('NP1_VALUE', mesh_np1_default),
    'inv_rfact0_block0': '1.0/Delta0block0',
    'inv_rfact1_block0': '1.0/Delta1block0',
    'shock_factor': os.getenv('SHOCK_FACTOR_VALUE', '1.0'),
}

ndim = 2
constants = ['Re', 'Pr', 'gama', 'Minf', 'Ml', 'RefT', 'SuthT']
coordinate_symbol = 'x'
conservative = True

block = SimulationBlock(ndim, block_number=0, conservative=conservative)
SimulationDataType.set_datatype(Double)

metriceq = MetricsEquation()
metriceq.generate_transformations(ndim, coordinate_symbol, [(True, True), (True, True)], 2)

EE = EinsteinEquation()
EE.optional_subs_dict = metriceq.metric_subs
# Curvilinear metric velocity mapping required by transformed operators.
for eq in EE.expand('Eq(U_i, D_i_j*u_j)', ndim, coordinate_symbol, [], constants):
    EE.optional_subs_dict[eq.lhs] = eq.rhs
# Hyper-dual lagrangian velocity mapping.
for eq in EE.expand('Eq(vl_i, u_i)', ndim, coordinate_symbol, [], constants):
    EE.optional_subs_dict[eq.lhs] = eq.rhs

HDV = HyperDualVelocitySplit(
    ndim,
    constants,
    coordinate_symbol=coordinate_symbol,
    conservative=conservative,
    viscosity='dynamic',
    include_skew_work=False,
    use_reynolds=True,
    split_type='KGP',
    energy_formulation='enthalpy',
)

simulation_eq = SimulationEquations()
simulation_eq.add_equations(HDV.mass)
simulation_eq.add_equations(HDV.momentum)
simulation_eq.add_equations(HDV.energy)

constituent = ConstituentRelations()
for eq in EE.expand('Eq(u_i, rhou_i/rho)', ndim, coordinate_symbol, [], constants):
    constituent.add_equations(eq)
for expr in [
    'Eq(p, (gama-1)*(rhoE - (1/2)*rho*(KD(_i,_j)*u_i*u_j)))',
    'Eq(T, p*gama*Minf*Minf/(rho))',
    'Eq(mu, (T**(1.5)*(1.0+SuthT/RefT)/(T+SuthT/RefT)))',
    'Eq(H, (rhoE + p) / rho)',
]:
    constituent.add_equations(EE.expand(expr, ndim, coordinate_symbol, [], constants))

simulation_eq.apply_metrics(metriceq)

# Initial freestream state.
q_vector = flatten(simulation_eq.time_advance_arrays)
d, u0, u1, p = symbols('d u0 u1 p', **{'cls': GridVariable})
gama, Minf = symbols('gama Minf', **{'cls': ConstantObject})
init_eq = [
    Eq(d, 1.0),
    Eq(u0, 1.0),
    Eq(u1, 0.0),
    Eq(p, 1.0/(gama*Minf**2.0)),
    Eq(q_vector[0], d),
    Eq(q_vector[1], d*u0),
    Eq(q_vector[2], d*u1),
    Eq(q_vector[3], p/(gama-1.0) + 0.5*d*(u0**2 + u1**2)),
]

initial = GridBasedInitialisation()
initial.add_equations(init_eq)

rk = RungeKuttaLS(4)
cent = StoreSome(4, 'u0 u1 T', merged=True)
block.set_discretisation_schemes({rk.name: rk, cent.name: cent})

# Boundary conditions.
boundaries = []
periodic_dir = int(os.getenv('PERIODIC_DIR', '0'))
if periodic_dir not in (0, 1):
    raise ValueError('PERIODIC_DIR must be 0 or 1')
radial_dir = 1 - periodic_dir
# Metric spacing must follow computational directions, not physical names.
# Direction tagged as periodic uses angular spacing, the other uses radial spacing.
r_inner = os.getenv('R_INNER_VALUE', '0.5')
r_outer = os.getenv('R_OUTER_VALUE', '20.0')
theta_span = os.getenv('THETA_SPAN_VALUE', '2.0*M_PI')
delta0_default = f'(({theta_span})/(block0np0))' if periodic_dir == 0 else f'(({r_outer}-{r_inner})/(block0np0-1.0))'
delta1_default = f'(({r_outer}-{r_inner})/(block0np1-1.0))' if periodic_dir == 0 else f'(({theta_span})/(block0np1))'
simulation_parameters['Delta0block0'] = os.getenv('DELTA0_VALUE', delta0_default)
simulation_parameters['Delta1block0'] = os.getenv('DELTA1_VALUE', delta1_default)
# Radial boundaries: wall + farfield
wall_gamma, wall_minf, Twall = symbols('gama Minf Twall', **{'cls': ConstantObject})
wall_energy = [Eq(q_vector[-1], q_vector[0]*Twall / (wall_gamma * wall_minf**2.0 * (wall_gamma - S.One)))]
wall_bc_type = os.getenv('WALL_BC_TYPE', 'zero_pressure_grad').strip().lower()
if wall_bc_type == 'isothermal':
    boundaries += [IsothermalWallBC(direction=radial_dir, side=0, equations=wall_energy)]
else:
    boundaries += [IsothermalWall_ZeroPressureGradBC(direction=radial_dir, side=0, equations=wall_energy)]
boundaries += [DirichletBC(direction=radial_dir, side=1, equations=init_eq)]
# Angular boundaries: periodic
periodic_corners = os.getenv('PERIODIC_CORNERS', '1') == '1'
periodic_full_depth = os.getenv('PERIODIC_FULL_DEPTH', '1') == '1'
boundaries += [PeriodicBC(direction=periodic_dir, side=0, halos=[-2, 2], corners=periodic_corners, full_depth=periodic_full_depth)]
boundaries += [PeriodicBC(direction=periodic_dir, side=1, halos=[-2, 2], corners=periodic_corners, full_depth=periodic_full_depth)]

block.set_block_boundaries(boundaries)

# Set core equations first so filters can query block metric class.
block.set_equations([constituent, simulation_eq, initial, metriceq])

# Optional dissipation controls
eq_classes = []
WF = None
if os.getenv('ENABLE_WENO', '0') == '1':
    WF = WENOFilter(
        block, order=5, formulation='Z', flux_type='LLF', airfoil=False, metrics=metriceq
    )
    eq_classes += WF.equation_classes
if os.getenv('ENABLE_TVD', '0') == '1':
    eq_classes += TVDFilter(block, airfoil=False).equation_classes
if eq_classes:
    block.set_equations(eq_classes)

# Optional stabilization filters (as used in existing cylinder workflows).
if os.getenv('ENABLE_SFD_FILTER', '1') == '1':
    sfd = SFD(block, chifilt=0.1, omegafilt=1.0 / 0.75)
    block.set_equations(sfd.equation_classes)

if os.getenv('ENABLE_BINOMIAL_FILTER', '1') == '1':
    j = block.grid_indexes[radial_dir]
    radial_np = int(simulation_parameters[f'block0np{radial_dir}'])
    grid_condition = j >= (radial_np - 4)
    bf = BinomialFilter(block, order=6, directions=[0, 1], grid_condition=grid_condition, sigma=0.2)
    block.set_equations(bf.equation_classes)

# IO
write_h5 = iohdf5(save_every=int(os.getenv('SAVE_EVERY_VALUE', '1000')), **{'iotype': 'Write'})
write_h5.add_arrays(simulation_eq.time_advance_arrays)
read_h5 = iohdf5(**{'iotype': 'Read'})
x, y = symbols('x0 x1', **{'cls': DataObject})
read_h5.add_arrays([x, y])
block.setio([write_h5, read_h5])

block.discretise()

# Extend periodic swaps to full WENO halo width.
if WF is not None:
    WF.update_periodic_boundary(block, halos=[-5, 5])

    def create_exchange_calls_codes(block, dsets):
        kernels = []
        arrays = [block.location_dataset(a) for a in flatten(dsets)]
        for direction in [periodic_dir]:
            for side in [0, 1]:
                BC = PeriodicBC(
                    direction, side, halos=[-5, 5],
                    corners=periodic_corners, full_depth=periodic_full_depth
                )
                kernels += [BC.apply(arrays, block)]
        return kernels

    filter_swaps = create_exchange_calls_codes(block, ['rho', 'rhou0', 'rhou1', 'rhoE'])
    for eq in block.list_of_equation_classes:
        if isinstance(eq, UserDefinedEquations) and eq.full_swap:
            eq.Kernels += filter_swaps

np0 = int(simulation_parameters['block0np0'])
np1 = int(simulation_parameters['block0np1'])
probe_locations = [
    (max(2, int(0.1 * np0)), max(2, int(0.1 * np1))),
    (max(2, int(0.5 * np0)), max(2, int(0.5 * np1))),
    (max(2, int(0.9 * np0)), max(2, int(0.9 * np1))),
]
SM = SimulationMonitor(
    [block.location_dataset('rho'), block.location_dataset('u0'), block.location_dataset('u1')],
    probe_locations,
    block,
    print_frequency=100,
    fp_precision=12,
    output_file='full_annulus_monitor.log',
)

alg = TraditionalAlgorithmRK(block, simulation_monitor=SM)
OPSC(alg, OPS_diagnostics=1)
if os.getenv('ENABLE_NAN_CHECK', '1') == '1':
    print_iteration_ops(NaN_check='rho', every=100, nblocks=1)
else:
    print_iteration_ops(every=100, nblocks=1)
substitute_simulation_parameters(simulation_parameters.keys(), simulation_parameters.values())
